#### Matrix Multiplication

In [1]:
import numpy as np

In [2]:
A = np.array([
    [4,9,9],
    [9,1,6],
    [9,2,3]
])

B = np.array([
    [2,2],
    [5,7],
    [4,4]
])

print("Matrix of A: \n", A)
print("Matric of B: \n", B)

Matrix of A: 
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matric of B: 
 [[2 2]
 [5 7]
 [4 4]]


You can multiply matrices  𝐴
  and  𝐵
  using NumPy package function np.matmul():

In [3]:
np.matmul(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

Which will output  3×2
  matrix as a np.array. Python operator @ will also work here giving the same result:

In [4]:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

#### Matrix Convention and Broadcasting

In [5]:
try:
    np.matmul(B, A)
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [6]:
try :
    B@A
except ValueError as err:
    print(err)    

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [7]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])

print("Shape of vector x:", x.shape)
print("Number of dimensions of vector x:", x.ndim)
print("Shape of vector x, reshaped to a matrix:", x.reshape((3, 1)).shape)
print("Number of dimensions of vector x, reshaped to a matrix:", x.reshape((3, 1)).ndim)

Shape of vector x: (3,)
Number of dimensions of vector x: 1
Shape of vector x, reshaped to a matrix: (3, 1)
Number of dimensions of vector x, reshaped to a matrix: 2


In [8]:
np.matmul(x,y)

np.int64(3)

In [9]:
try:
    np.matmul(x.reshape((3,1)), y.reshape((3,1)))
except ValueError as err:
    print(err)    

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)


In [10]:
np.dot(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [11]:
A-2

array([[ 2,  7,  7],
       [ 7, -1,  4],
       [ 7,  0,  1]])